# Generated by Django 4.0.1 on 2023-02-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_remove_user_all_email_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=150)),
                ('last_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number_1', models.CharField(db_index=True, max_length=30)),
                ('phone_number_2', models.CharField(db_index=True, max_length=30)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'verbose_name': 'SecondaryContacts',
                'verbose_name_plural': 'SecondaryContacts',
            },
        ),
    ]
