# Generated by Django 4.0.1 on 2023-02-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_remove_user_all_email_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.CharField(db_index=True, max_length=255, null=True)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=9, null=True)),
                ('current_stock', models.IntegerField(db_index=True, default=10, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.CharField(db_index=True, max_length=255, null=True)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=9, null=True)),
                ('billable', models.BooleanField(default=True)),
                ('always_add_to_projects', models.BooleanField(default=False)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
