# Generated by Django 4.0.1 on 2023-02-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='invoice_goods',
            field=models.ForeignKey(db_column='invoice_goods_id', on_delete=django.db.models.deletion.CASCADE, to='clients.invoicegoods'),
        ),
    ]
