# Generated by Django 4.0.1 on 2023-02-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_logged_in_and_more'),
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='invoice_goods',
        ),
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(db_index=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='always_add_to_projects',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='billable',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(db_index=True, decimal_places=3, max_digits=6)),
                ('name', models.CharField(db_index=True, max_length=20, null=True)),
                ('number', models.CharField(db_index=True, max_length=30, null=True)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'verbose_name': 'SalesTax',
                'verbose_name_plural': 'SalesTaxes',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sales_taxes',
            field=models.ManyToManyField(to='business.SalesTax'),
        ),
        migrations.AddField(
            model_name='service',
            name='sales_taxes',
            field=models.ManyToManyField(to='business.SalesTax'),
        ),
    ]
