# Generated by Django 4.0.1 on 2023-06-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_business_customer_offer_customized_type_and_more'),
        ('business', '0003_remove_service_invoice_goods_item_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='business',
            field=models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
    ]
