# Generated by Django 4.0.1 on 2023-06-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_alter_item_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(db_index=True, max_length=50)),
                ('issued_date', models.CharField(db_index=True, max_length=20)),
                ('due_date', models.CharField(db_index=True, max_length=20)),
                ('optional', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('currency', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=150, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=30, null=True)),
                ('country', models.CharField(db_index=True, max_length=50, null=True)),
                ('address_1', models.CharField(db_index=True, max_length=255, null=True)),
                ('address_2', models.CharField(db_index=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('state', models.CharField(db_index=True, max_length=255, null=True)),
                ('postal_code', models.CharField(db_index=True, max_length=20, null=True)),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('currency', models.CharField(db_index=True, max_length=100)),
                ('sales_taxes', models.ManyToManyField(to='business.SalesTax')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('merchant', models.CharField(db_index=True, max_length=150)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('grand_total', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('assign_to', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('recurring', models.BooleanField(db_index=True, default=False)),
                ('currency', models.CharField(db_index=True, max_length=100)),
                ('sales_taxes', models.ManyToManyField(to='business.SalesTax')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('rate', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(blank=True, db_index=True, default=10, null=True)),
                ('bill', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, to='expenses.bills')),
                ('sales_taxes', models.ManyToManyField(to='business.SalesTax')),
            ],
            options={
                'verbose_name': 'BillLineItem',
                'verbose_name_plural': 'BillLineItems',
            },
        ),
    ]
