# Generated by Django 4.0.1 on 2023-07-12 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_ujian'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='business',
            field=models.ForeignKey(db_column='business_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='business',
            field=models.ForeignKey(db_column='business_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business_id', to='accounts.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='business',
            field=models.ForeignKey(db_column='business_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
            preserve_default=False,
        ),
    ]
