# Generated by Django 4.0.1 on 2023-07-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_bills_business_data_business_vendor_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
