# Generated by Django 4.0.1 on 2023-02-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_all_email_notifications_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='business',
            field=models.ForeignKey(db_column='business_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
            preserve_default=False,
        ),
    ]
