# Generated by Django 4.0.1 on 2023-02-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_email_user_email_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'EmailNotification', 'verbose_name_plural': 'EmailNotifications'},
        ),
    ]
