# Generated by Django 4.0.1 on 2023-02-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_logged_in_and_more'),
        ('notifications', '0003_alter_email_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='business',
            field=models.OneToOneField(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
    ]
