# Generated by Django 4.0.1 on 2023-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_business_address_1_alter_business_address_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Business'},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
