# Generated by Django 4.0.1 on 2023-01-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_business_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
