# Generated by Django 4.0.1 on 2023-01-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
