# Generated by Django 4.0.1 on 2023-02-11 06:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_owner_id_business_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=accounts.models.profile_upload_path),
        ),
    ]
