# Generated by Django 4.0.1 on 2023-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_name',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_number',
            field=models.CharField(db_index=True, max_length=21, null=True),
        ),
    ]
