# Generated by Django 4.0.1 on 2023-02-15 19:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_business_tax_name_business_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(db_index=True, default='#4f697a', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_font',
            field=models.CharField(db_index=True, default='Modern (Helvetica)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_logo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=accounts.models.theme_upload_path),
        ),
    ]
