# Generated by Django 4.0.1 on 2023-02-21 13:39

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_all_email_notifications_user_theme_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='all_email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_font',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_logo',
        ),
        migrations.AddField(
            model_name='business',
            name='all_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='theme_color',
            field=models.CharField(db_index=True, default='#4f697a', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='theme_font',
            field=models.CharField(db_index=True, default='Modern (Helvetica)', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='theme_logo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=accounts.models.theme_upload_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
