# Generated by Django 4.0.1 on 2023-06-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_logged_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='registration_date',
        ),
    ]
