# Generated by Django 4.0.1 on 2023-06-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ujian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ujian',
        ),
    ]
