# Generated by Django 4.0.1 on 2023-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
