# Generated by Django 4.0.1 on 2023-02-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_remove_user_all_email_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=150, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=150, null=True)),
                ('company_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=30, null=True)),
                ('business_phone', models.CharField(db_index=True, max_length=30, null=True)),
                ('mobile_phone', models.CharField(db_index=True, max_length=30, null=True)),
                ('country', models.CharField(db_index=True, max_length=50, null=True)),
                ('address_1', models.CharField(db_index=True, max_length=255, null=True)),
                ('address_2', models.CharField(db_index=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('state', models.CharField(db_index=True, max_length=255, null=True)),
                ('zip_code', models.CharField(db_index=True, max_length=20, null=True)),
                ('tax_name', models.CharField(db_index=True, max_length=10, null=True)),
                ('tax_number', models.CharField(db_index=True, max_length=21, null=True)),
                ('send_payment_reminders', models.BooleanField(default=False)),
                ('charge_late_fees', models.BooleanField(default=False)),
                ('percentage_invoice_value', models.BooleanField(default=False)),
                ('percentage_outstanding_balance', models.BooleanField(default=False)),
                ('flat_fee', models.BooleanField(default=False)),
                ('late_fee_amount', models.IntegerField(db_index=True, default=10, max_length=5)),
                ('number_days', models.IntegerField(db_index=True, default=30, max_length=5)),
                ('currency', models.CharField(db_index=True, default='GBP', max_length=100)),
                ('language', models.CharField(db_index=True, default='English', max_length=50)),
                ('invoice_attachments', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.CharField(db_index=True, max_length=20)),
                ('due_date', models.CharField(db_index=True, max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=25, null=True)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=20)),
            ],
            options={
                'verbose_name': 'ClientsInvoice',
                'verbose_name_plural': 'ClientsInvoices',
            },
        ),
        migrations.CreateModel(
            name='SecondaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=150)),
                ('last_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number_1', models.CharField(db_index=True, max_length=30)),
                ('phone_number_2', models.CharField(db_index=True, max_length=30)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'verbose_name': 'ClientsSecondaryContact',
                'verbose_name_plural': 'ClientsSecondaryContacts',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_days', models.IntegerField(db_index=True, default=5, max_length=5)),
                ('due_date', models.CharField(db_index=True, default='after', max_length=10)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.data')),
            ],
            options={
                'verbose_name': 'ClientsPaymentReminder',
                'verbose_name_plural': 'ClientsPaymentReminders',
            },
        ),
        migrations.CreateModel(
            name='InvoiceGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.CharField(db_index=True, max_length=255, null=True)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=9, null=True)),
                ('quantity', models.IntegerField(db_index=True, default=10, max_length=5, null=True)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'verbose_name': 'InvoiceGoods',
                'verbose_name_plural': 'InvoiceGoods',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='clients.invoice')),
                ('invoice_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.invoicegoods')),
            ],
            options={
                'verbose_name': 'ClientsInvoiceDetail',
                'verbose_name_plural': 'ClientsInvoiceDetails',
            },
        ),
    ]
