# Generated by Django 4.0.1 on 2023-02-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_logged_in_and_more'),
        ('business', '0003_remove_service_invoice_goods_item_business_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='business',
            field=models.ForeignKey(db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed_to',
            field=models.ForeignKey(db_column='billed_to', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AddField(
            model_name='invoicegoods',
            name='invoice',
            field=models.ForeignKey(db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.invoice'),
        ),
        migrations.AddField(
            model_name='invoicegoods',
            name='sales_taxes',
            field=models.ManyToManyField(to='business.SalesTax'),
        ),
        migrations.AlterField(
            model_name='data',
            name='charge_late_fees',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='flat_fee',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='invoice_attachments',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='late_fee_amount',
            field=models.IntegerField(db_index=True, default=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_days',
            field=models.IntegerField(db_index=True, default=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='percentage_invoice_value',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='percentage_outstanding_balance',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='send_payment_reminders',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='quantity',
            field=models.IntegerField(db_index=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='number_days',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
    ]
