# Generated by Django 4.0.1 on 2023-04-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_data_business_invoice_billed_to_invoice_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='late_fee_amount',
            field=models.IntegerField(blank=True, db_index=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_days',
            field=models.IntegerField(blank=True, db_index=True, default=30, null=True),
        ),
    ]
