# Generated by Django 4.0.1 on 2023-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreminder',
            name='personal_message',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
