# Generated by Django 4.0.1 on 2023-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_data_relationship_note_alter_data_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='quantity',
            field=models.IntegerField(blank=True, db_index=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='rate',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='phone_number_1',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='phone_number_2',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
