# Generated by Django 4.0.1 on 2023-05-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_logged_in_and_more'),
        ('clients', '0007_alter_invoice_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycontact',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.AlterField(
            model_name='invoicegoods',
            name='business',
            field=models.ForeignKey(db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='business',
            field=models.ForeignKey(db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
    ]
