# Generated by Django 4.0.1 on 2023-06-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_item_business'),
        ('accounts', '0014_alter_business_customer_offer_customized_type_and_more'),
        ('clients', '0009_invoicelineitem_alter_data_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'verbose_name': 'InvoiceLineItem', 'verbose_name_plural': 'InvoiceLineItems'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billed_to',
            field=models.ForeignKey(db_column='billed_to', on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='clients.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='rate',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='business',
            field=models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
        ),
        migrations.CreateModel(
            name='Retainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(db_index=True, max_length=20)),
                ('period', models.CharField(db_index=True, max_length=10)),
                ('fees_per_period', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('hours_per_period', models.DecimalField(db_index=True, decimal_places=2, max_digits=9)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('issued_date', models.CharField(db_index=True, max_length=20)),
                ('number_invoices', models.CharField(db_index=True, max_length=30)),
                ('invoice_delivery', models.CharField(db_index=True, max_length=60)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('discount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True)),
                ('billed_to', models.ForeignKey(db_column='billed_to', on_delete=django.db.models.deletion.CASCADE, to='clients.data')),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('sales_taxes', models.ManyToManyField(to='business.SalesTax')),
            ],
            options={
                'verbose_name': 'Retainer',
                'verbose_name_plural': 'Retainers',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('discount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True)),
                ('notes', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('esignature', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.data')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
        migrations.CreateModel(
            name='EstimateProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_estimate', models.BooleanField(db_index=True, default=True)),
                ('estimate_proposal_number', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rate', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(blank=True, db_index=True, default=10, null=True)),
                ('sales_taxes', models.ManyToManyField(to='business.SalesTax')),
            ],
            options={
                'verbose_name': 'EstimateProposalLineItem',
                'verbose_name_plural': 'EstimateProposalLineItems',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('discount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True)),
                ('notes', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.data')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
            },
        ),
    ]
