# Generated by Django 4.0.1 on 2023-06-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_invoicelineitem_options_invoice_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
