# Generated by Django 4.0.1 on 2023-06-13 09:14

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_invoice_notes_invoice_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='theme_color',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='theme_font',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='theme_logo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=clients.models.theme_upload_path),
        ),
    ]
