# Generated by Django 4.0.1 on 2023-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_invoice_recurring_invoice_theme_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='theme_color',
            field=models.CharField(db_index=True, default='#4f697a', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='theme_font',
            field=models.CharField(db_index=True, default='Modern (Helvetica)', max_length=20),
        ),
    ]
