# Generated by Django 4.0.1 on 2023-06-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_invoice_theme_color_alter_invoice_theme_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to',
        ),
        migrations.RemoveField(
            model_name='retainer',
            name='billed_to',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(db_column='client_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retainer',
            name='client',
            field=models.ForeignKey(db_column='client_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.data'),
            preserve_default=False,
        ),
    ]
