# Generated by Django 4.0.1 on 2023-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_invoice_billed_to_remove_retainer_billed_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
