# Generated by Django 4.0.1 on 2023-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_company',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
