# Generated by Django 4.0.1 on 2023-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_invoice_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='online_payments',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
