# Generated by Django 4.0.1 on 2023-06-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_invoice_online_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_company',
        ),
    ]
