# Generated by Django 4.0.1 on 2023-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_remove_invoice_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(db_index=True, default='USD — US Dollar', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='language',
            field=models.CharField(db_index=True, default='English', max_length=50),
        ),
    ]
