# Generated by Django 4.0.1 on 2023-07-03 10:04

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_invoice_currency_invoice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='theme_logo',
            field=models.ImageField(blank=True, db_index=True, max_length=255, null=True, upload_to=clients.models.theme_upload_path),
        ),
    ]
