# Generated by Django 4.0.1 on 2023-07-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_remove_estimateproposallineitem_is_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=255, unique=True),
        ),
    ]
